# Generated by Django 5.1.4 on 2026-05-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('transport', 'Transport'), ('service', 'Service')], max_length=20)),
                ('request_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, db_column='accepted_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service_details', serialize=False, to='requests_app.request')),
                ('service_category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service_details',
            },
        ),
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('request', models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transport_details', serialize=False, to='requests_app.request')),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transport_details',
            },
        ),
    ]
