# Generated by Django 5.1.4 on 2026-05-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
